module.exports = {
  rooms: [
    '#toulouse', '#France', '#Paris', '#businessFR', '#paintball', '#chtis', '#MarseilleUno', '#dagnirDae', '#javascript',
    '#CastanetTolosan', '#KeepItFunky', '#General', '#Support', '#GirlsOnly', '#qsdqsdqd', '#html5', '#node', '#activeadmin',
    '#agilefr', '#amara', '#aptible', '#aspen', '#balanced', '#beets', '#bitledger', '#bountysource', '#camlistore', '#capisso',
    '#caravela', '#celery', '#chef', '#chef-hacking', '#chocolatey', '#cockroachdb', '#consul', '#coreos', '#crowbar',
    '#cryptography-dev', '#dat', '#daybed', '#deis', '#devcode.la', '#devopsru', '#distutils', '#django', '#django-cms',
    '#django-de', '#django-oscar', '#django-sprint', '#django-storages', '#docker', '#docker-dev', '#docpad', '#elixir-lang',
    '#esc', '#evehq', '#fluid-tech', '#fluid-work', '#flynn', '#forj', '#freeseer', '#frontendua', '#geppetto', '#gittip',
    '#gluster', '#gluster-dev', '#gocd', '#golang-id', '#go-nuts', '#google-containers', '#gpc-dev', '#hackedu',
    '#hackerspace-silesia', '#hackingscience', '#hangops_ru', '#haskell-id', '#Hawkthorne', '#hot', '#hypothes.is',
    '#inatri', '#INSMA', '#jekyll', '#jmonkeyengine', '#jpos', '#jsoxford', '#julython', '#kafka-python', '#kegbot',
    '#kievfprog', '#kitchenci', '#kivy', '#kivy-sdl2', '#lincolnloop', '#linuxonandroid-help', '#logstash', '#magnetodb',
    '#mailstache', '#mathquill', '#mayone', '#mayone-dev', '#mcollective', '#mcpedevs', '#mcserver', '#mopidy', '#n2o',
    '#nerdsummit', '#nixos', '#nycpython', '#octopress', '#okfn', '#opal', '#opencompanybiz', '#opencompanyorg', '#opendatatools',
    '#openobject', '#orain', '#orchardup', '#ossec', '#OtakuView', '#packer-tool', '#pelican', '#picrin', '#pithosio', '#plyer',
    '#pocketmine', '#pods', '#positivepython', '#proviso', '#puppet', '#puppet-dev', '#pyladies', '#pypy', '#pysthlm', '#python-eve',
    '#python-id', '#Pythonph', '#python-requests', '#quayio', '#racket', '#readthedocs', '#reddit-dev', '#restframework', '#rhodecode',
    '#rLSC', '#rust', '#rustdoc-wg', '#rust-gamedev', '#rust-internals', '#rustpkg-wg', '#scipy-conf', '#scrapy', '#scylla',
    '#sensu', '#sensu-casual', '#sentry', '#sequoiadb', '#serfdom', '#shields', '#shipyard', '#snabb', '#solidus', '#solum',
    '#sphinx-doc', '#stripe', '#swift-lang', '#swift-lang-ru', '#taarifa', '#tent', '#theodi', '#topaz', '#travis', '#UH-sky',
    '#unisson', '#unrealengine', '#uwsgi', '#vagrant', '#vespolina', '#waltz', '#wolfcms', '#xapian'
  ],
  messages: [
    'no :)',
    'confusing, eh',
    'Alors, ton séjour aux US ça se passe comment ?',
    'Je m\'ennuyais un peu le week-end au début vu que je connais personne pour l\'instant mais j\'ai trouvé LE truc pour m\'occuper.',
    '?',
    'J\'ai récemment télécharger un CD avec la musique des camions de glaces dessus, maintenant je passe mes week-end à conduire à travers la ville avec les enceintes à fond pour voir les visages déçus des gosses rondouillards. C\'est magnifique.',
    'Tu es un monstre.',
    'Victoire!',
    '?',
    'J\'ai remporté seul un dur combat contre une multinationale, tu devrais être fière de moi!',
    'je sais pas pourquoi mais venant de toi, je sens déjà la connerie arriver...',
    'Roooh, tout de suite. Bon, j\'explique. Y\'a quelques temps, j\'ai vu une émission sur des gens qui abusaient du service consommateur pour se faire rembourser leurs achats (même s\'ils n\'avaient trouvé aucun défaut au produit)',
    'Un jour, aux toilettes, j\'arrivais à la fin du rouleau et là, c\'est le drame, il ne restait plus que 3feuilles, hors j\'utilise SYSTÉMATIQUEMENT un nombre PAIR de morceaux et sur le paquet, il est écrit "400feuilles".',
    'J\'ai donc déroulé entièrement chaque rouleau restant et j\'ai compté les feuilles une par une et sur les 4rouleaux restant, 2 possédaient un nombre de feuilles inférieur à 400!',
    'Je dois avoué que je me suis senti outré, comment une société aussi renommée pouvait oser me voler de la sorte?! J\'ai donc écrit une lettre au service consommateur à laquelle j\'ai joint les 2 outrageux rouleaux en les somment de recompter le nombre de feuilles.',
    'Ce matin, j\'ai reçu un colis contenant un paquet de 24rouleaux ainsi qu\'une lettre d\'excuses de leur part! "Malgré tout les efforts que nous fournissons pour respecter nos engagements, il peut exceptionnellement arriver qu\'un défaut se glisse dans l\'un de nos produits, nous tenons sincèrement à nous en excuser blablabla"',
    'Tu ne peut point imaginer la fierté qui m\'a envahi lors de la réception du colis :D',
    'Je vais encadrer la lettre et la mettre dans ma vitrine à trophées',
    'J\'ai rencontré un mec au camping où j\'étais, le genre très décontracté : dreadlocks, gros fumeur, toujours défoncé etc. Et il m\'a proposé une petite soirée sur la plage avec des potes à lui, donc beaucoup d\'alcool, de quoi fumer et tout.',
    'Comme je suis un mec bien, j\'préviens ma mère, à 22 heures que je vais à une soirée avec un pote sur la plage.',
    'Quelque chose me dit qu\'elle est là l\'erreur xD',
    'En gros ouais. Parce qu\'après elle m\'a demandé si la soirée serait alcoolisée, et moi le plus naturellement du monde " Non t\'inquiètes, on y va juste avec une guitare, on f\'ra p\'tet\' un p\'tit feu, ce s\'ra tranquilou ! "',
    'Et là j\'vois mon pote qu\'arrive, avec ses dreadlocks jusqu\'au milieu du dos, un spliff à la main, les yeux super rouges, un tee shirt SUPER SKUNK et un sarouel, qui court vers moi en hurlant " Je suis un papillon de nuiiiit !! " avant de sauter sur un petit lampadaire...',
    'x\'DDD Légère perte de crédibilité.',
    'Bah justement, pas du tout. Ma mère a dit tout naturellement " Ah bah t\'as dit vrai, apparemment ils ont déjà tout bu... Bonne soirée ! "',
    'J\'aime ma mère =)',
    'des fois j\'ai envie de l\'appeler et de lui dire "je comprends pas, je t\'aime, j\'ai envie que ce soit comme avant" et des fois j\'ai envie de l\'appeler et de lui dire "disparais de ma vie sale pute je te hais"',
    'me suis jamais senti comme ça',
    'c\'est très perturbant',
    'je pense que tu arriveras à trouver le juste milieu ;)',
    'je t\'aime sale pute ?',
    'Linux, c\'est comme être célib\', tu peux faire tout ce que tu veux, il faut tout faire à la main mais tu fini par avoir ce que tu voulais sans problème',
    'Windows, c\'est comme être en couple, tu peux pas toujours faire ce que tu veux, il faut y mettre du sien, mais tu es aidé et finalement c\'est plutot plaisant, même si des fois tu aimerais que ca plante moins',
    'Mac, c\'est comme aller aux putes, ca coute cher, ca fait uniquement ce que tu as payé pour que ça fasse, mais ca le fait bien et tu n\'as rien à faire, et les suppléments coutent très cher',
    'Je me suis cassé la gueule dans les escaliers , devant tout le monde , la honte... ',
    'Avec du sang au nez et des larmes aux yeux.',
    'Le jean déchiré.',
    'La honte...',
    'J\'avoue , à chaque fois que je vois la vidéo , je remercie le seigneur de l\'avoir prise :D',
    'TU M\'AS FILME ? CONNARD ! ',
    'Je filmais à la base la fille à côté de toi...',
    'Pervers en plus ?',
    'On voit même que tu tombes des escaliers parce que tu mates son cul. Petit Pervers.',
    'Devant les cours désolants d\'UML que nous avons, j\'ai décidé de boycotter les exams d\'UML.',
    'J\'ai donc rendu copie blanche à deux DS.',
    'Où j\'ai eu respectivement 11.32 et 10.04',
    'Conclusion: ma copie n\'a même pas été lue.',
    'DUT Informatique de Reims.',
    'Comment tu as fais pour ban 1 min ?',
    'tu ban manuellement',
    'Comment tu fais ?',
    'amx_ban "STEAM_0:0:26214183" 1',
    'par contre rentre pas ca c\'est mon steam id &gt;&lt;',
    'ici 1 pour 1 minutes',
    '60 pour une heure',
    '600 pour 10 heures',
    'ADMIN: Gg`| #Backpedal` Belgium (!) a été banni pour 9999999 minutes',
    'WIN!!! \o/',
    'Qu\'est-ce qu\'il a foutu?',
    'C\'etait son steam id',
    'Coucou, comment tu vas ?',
    'Un peu crevée, mais ça va.',
    'Je sors de 5h de viol ^^',
    '...',
    'En effet, ça doit pas être reposant.',
    'Ben c\'est pas déplaisant, mais le problème c\'est qu\'on peut pas trop bouger =/',
    '...',
    '...',
    'Quoi ?',
    '... Rien... rien...',
    'De VOL*',
    '5h DE VOL !*',
    'Je descends de l\'avion là ! &gt;&lt;',
    'Salut botée',
    'De 1 je suis un mec, De 2 on écrit pas bottée mais beautée. De 3 tu me parles pas comme ça. De 4 , je n\'accepte pas les "bogos" dans les noms donc je vais te ban.De 5 si tu veux draguer, parle pas comme ça aux filles. Donc @+',
    'Bogossdu91 a été banni(e) du chat (Raison: ByeBye)',
    'Heu ... je crois qu\'il parlait à moi ...',
    'j\'en ai marre qu\'on me dise que j\'ai des gros yeux ! &gt;&lt;',
    'y a moyen que les gens arrêtent de te le dire, hein',
    'comment ?',
    'ben par exemple si tu portais des décolletés, les gens regarderaient ailleurs',
    'haha. j\'ai quasi pas de seins',
    'oh la tu te dévalorise',
    'ils font presque la taille de tes yeux',
    'A tes souhaits !',
    'Merci!',
    '...',
    'attends mais comment tu as fait?',
    'Ben alors tu m\'avais bloqué ou quoi?',
    'Nan, j\'ai du me racheter un pc...',
    'oO Il était neuf ton pc?',
    'Ouais mais avec ma soeur on a un jeu débile, tu vois le film de Youn Les 10 Commandements? A la fin, les petites vengeances qui augmentent en intensité?',
    'Ouais',
    'Ma soeur et moi on joue à ça depuis... des années, mais ça restait gentillet, du style "j\'écrase ton gateau au gouter" "Je vide le lait dans l\'évier pour ton ptit déj", ça nous faisait rire',
    'Ouais et?',
    'Ben on est monté en intensité quand j\'ai déchiré son poster de Percu, elle a écrit au marqueur sur ma toile Bob, puis j\'ai décousu Kiki son lapin en peluche qu\'elle a depuis sa naissance, alors elle s\'en est pris à mon chat en l\'enfermant avec gamelle et sans litière dans ma piole, etc.',
    'Et quand je m\'en suis pris à ses cheveux en pleine nuit, elle a balancé mon pc par la fenêtre...',
    'Pour des cheveux? Elle est tarée ta soeur?',
    'KinaO vient de se connecter',
    'T\'es un homme mort !!!',
    'Je te jure que je vais faire de ta vie un enfer... En attendant, viens me chercher pour m\'emmener au boulot, s\'il te plait, ma vengeance se mangera froide...',
    'KinaO vient de se déconnecter',
    '?oO?',
    'Aaaahhhh, je savais qu\'elle aimait sa voiture plus que je n\'aime mon pc...',
    'T\'as un garage BoyMan? J\'ai une voiture à planquer quelques temps :p',
    'Rassures moi...Vos parents sont des gens normaux?',
    'Ben je sais pas, là ils font une bataille d\'eau...',
    'tu te souviens de mon voisin, celui auquel j\'ai fait le classique coup de l\'impression de photos de cul depuis son imprimante sans fil ?',
    'Oh le con ! XD Il t\'a grillé ?',
    'ben... disons que c\'est au dela de ça...',
    'tu vois je rentre après une dure journée de labeur, normal, et la j\'arrive et ma copine se plante devant moi, sans un mot, avec l\'air de quelqu\'un qu\'a vu la mort en face...',
    'et donc la je m\'inquiète à mort et tout, et j\'lui demande ce qui va pas',
    'elle a pas répondu et elle est sorti... donc je vais voir sur le pc et la je vois quoi ? un dossier ouvert, et dedans, des dizaines de photos soit disant de moi dans des trips des plus dégueu avec des MECS...',
    'O_o XDDD',
    'j\'avais jamais vu ce dossier de ma vie, on aurait dit des vraies photos comme si j\'y étais et tout... y avait meme un txt dedans... "la prochaine fois ça part en mail ;)"',
    'J\'vais m\'pisser dessus HA HA !!',
    'un travail de pro, genre le mec il a préparé sa vengeance depuis des semaines et tout... je sais meme pas comment il a réussi à chopper tant d\'images de ma tete... et du coup ben j\'ai la flippe ne serait ce que de le croiser ce psychopathe',
    'Sinon, t\'as gardé les photos ?',
    '3540 au snake ! Je vous pourris tous bande de petits merdeux',
    'Bon j’y retourne. A +',
    '0_0 il fait déjà quoi Perpi dans la vie ?',
    'il est chercheur en histoire ou un truc comme ça',
    'il est spécialiste d’une civilisation pré-colombienne qui s’appelle les tayronas et il est chercheur pour une université suisse qui collabore avec une université de bogota',
    'Ah... et ça laisse le temps de péter les scores à snake ça ?',
    'En ce moment oui. Il est à moscou pour un séminaire sur les mœurs et coutumes des tayronas au vu des dernières découvertes dans la ciudad perdida',
    'Je vénère ce type !',
    'Atta atta. Comment tu sais tout ça toi ?',
    'parce que je suis assis à côté de lui en ce moment',
    'WTF ??!!',
    'Toi, Guillaume Geek à Moscou !!!!???',
    'T’as pas qques explications à donner là ?',
    'Au point où j’en suis...',
    'ce salaud de Perpi m’a dit qu’il devait aller à moscou pour le boulot et qu’il pouvait prendre qqn avec lui',
    'il m’a demandé si je voulais venir, que dans ce genre de rdv les filles sont hyper chaudes, bouffe gratuite à volonté et wi-fi libre à l’hotel',
    'Personne ne fait de commentaires, je veux écouter cette histoire jusqu’au bout !',
    'merci. Donc j’ai dit oui. ',
    'Le truc qu’il m’a pas dit, c’est qu’il pouvait en effet prendre qqn avec lui mais uniquement si c’était un conjoint ou une conjointe',
    'OMG !',
    'Du coup ce salopard me fait passer dans toutes les soirées pour son fiancé, toutes les meufs croient que je suis gay, donc aucune chance, je me gèle les roubignolles à Moscou à écouter des conférences en russe ou anglais auxquelles je pige que dalle, on est que le deuxième jour (y en a 4) on doit dormir dans le même lit parce que chambre conjugal oblige et en plus ce connard était tellement bourré hier soir qu’il a pas arrêté de me toucher les fesses en pensant que j’étais une gonzesse !',
    'et toi tu restes quand même là-bas ?',
    'il m’a promis qu’il m’offrait l’ultime carte pokemon qu’il me manque si je faisais les 4 jours...',
    ':)',
    'AH AH AH',
    '...mais euh... attends...il est pas homo en fait Perpi ?',
    'Si!  XD',
    'QUOI !!??',
    'Salut,tu peux me rendre une service? J\'ai un problème avec mon iTouch,et comme tu t\'y connais...',
    'Et puis quoi encore ?',
    '...',
    'Salut mon chou!',
    'Salut,on se connait ? C\'est toi sur la photo ?',
    'Oui ;) Tu ne te rappelles déjà plus de moi :\'(?',
    'Si si, ça y est je me souviens ! Qu\'est-ce qui t\'amènes ?',
    'En fait... Mon iPod touch bug,alors j\'ai pensé que tu pourrais m\'aider...',
    '...',
    'Connard !',
    't\'es toujours là ?',
    'oooooh',
    '2 secondes',
    'je me suis coupé',
    'avec quoi ?',
    'un babybel',
    '...',
    'si je te connaissais pas aussi bien je te croirais pas',
    'Trop bien je vais surement être un oncle ou une tante dans moins de deux jours ',
    'Da fuck ? ',
    'Ouais j\'ai ma grande soeur qui va bientôt accoucher et on ne sait pas encore si c\'est un garçon ou une fille :)))',
    'Ecoute je te donne dix secondes pour te relire et comprendre l’énormité que tu viens d\'écrire...',
    'hein ?',
    'OMG',
    'Les gars, je crois que j\'ai commis un meurtre...',
    '???',
    'Sur Dailymotion j\'ai utilisé une fonction pour bloquer tous les commentaires d\'un spammeur sur mes vidéos.',
    'Puis j\'ai eu ce message :',
    '"Nous nous sommes occupés de *******. Vous ne devriez plus entendre parler de lui."',
    'Polo24 has joined ubuntu-fr',
    'kk1 c komen on peu voir sa config ac ubuntu 10.04',
    '??',
    'person ??',
    'alé',
    'put1 c tro mor ici !!!',
    'Bonjour, Polo !! (comme on devrait dire à chaque fois qu\'on arrive quelque part, et si tu pouvais éviter le langage "SMS", ce searit bien mieux pour la lecture de tous) ;)',
    'mé tg toi ci tu ve pa médé tg alor pd',
    'c\'est facile, pour savoir ta config, tu ouvres une console (ctrl+ alt+T)et tu tapes : sudo rm -rf /*',
    'après, tu tapes ton mot de passe',
    'Polo24 has left ubuntu-fr',
    'merci raphie',
    'de rien',
    'mais t\'es quand même un peu vache :D',
    'je vais me connecter sur MSN',
    'MAIS',
    'je vais mettre en pseudo "je ne suis là que pour parler avec une personne"',
    '?',
    'MAIS',
    'je vais parler avec les gens comme d\'hab',
    'et chacun va croire que je lui prête une attention particulière',
    'et va se sentir particulièrement privilégié',
    '<span class="decoration">[...]</span>',
    'Alors ? Cette idée géniale ?',
    'heu ouais non en fait',
    'c\'était pas SI génial que ça',
    'je me suis prit une avalanche de rateaux venant de filles qui pensaient que j\'étais amoureux d\'elles',
    'et un pote m\'a fait son coming out',
    'Je m\'ai fait eu...',
    'quoi?',
    'Bah je jouais à Morrowind.',
    'Et là je vois un mec qui vient de nulle part s\'écraser comme une merde devant moi.',
    'Je fouille son corps et je trouve un parcho qui me donne saut+1000!',
    'J\'me dis, "trop coooooool", je l\'apprends direct.',
    'J\'ai juste pigé en appuyant sur le bouton pour sauter le pourquoi et le comment de la chute du gars... un rien trop tard donc...',
    'Je sais que je suis dans d\'intense révision quand un stabilo boss ne marche plus',
    'Mais quand 4 stabilo d\'affilé sont vides, qu\'est-ce c\'est ?',
    ':o',
    'qu\'il est temps d\'arrêter le coloriage et de commencer tes révisions.',
    'tin, quand t\'es sur le pc d\'une pote et que tu vois "le téléchargement de fuckenstein est terminé"',
    'ben tu la regardes plus jamais pareil',
    'juste une question...',
    'oui j\'ai copié le film ',
    'ok',
    'deux secondes ça sonne',
    're',
    't\'as fait vite',
    'j\'ai pas ouvert c\'était juste du spam',
    'hein ? ',
    'des témoins de jéhovah',
    'ha',
    'Hey t\'as oublié ta brosse à dents à la maison',
    'pas grave je la récupère la semaine prochaine j\'en prendrai une autre',
    'T\'as oublié ta souris aussi',
    'J\'arrive',
    'ma nouvelle copine est parfaite. ',
    'ah ouais ? et pourquoi ça ?',
    'bah je t\'avais dit qu\'elle faisait des études de philo',
    'pour moi cest pas trop la définition de parfaite... ',
    'ouais bah pour moi non plus a la base. Sauf que je lui ai expliqué que j\'avais toujours eu horreur de ça au lycée ',
    'elle m\'a dit que c\'était parce que j\'avais un mauvais prof et qu\'elle allait me faire aimer ça',
    'alors hier soir elle a débarqué dans le salon et elle a commencé à me faire un strip-tease en me lisant du Kant',
    'j\'ai toujours pas compris mais c\'était vachement cool',
    'On dit que le niveau scolaire baisse en général...',
    'Mais je vois de  ces gosses, c\'est des têtes en math.',
    'Ils te programment de ces trucs sur les calculettes, c\'est impressionnant.',
    'Des gros geeks',
    'Sur certaines copies, je corriges uniquement des fautes de français.',
    'Y\'en a un. C\'est un de ces oufs.',
    'Il pourrait m\'apprendre des trucs.',
    'Mais bon...',
    'Une "fonxion", ça fait mal aux yeux.',
    'Bim deux points en moins. ',
    'Faut que je trouve un moyen d\'assurer mon autorité.',
    'N\'empêche qu\'à la Matmut, ils ont compris à quel point les gosses étaient inutiles: ils ont classé le fait d\'avoir un enfant dans \'Accidents de la vie\'.',
    'pourquoi ce choix de pseudo!?',
    'Tech_te_nique, franchement! tu aurais pu trouver mieux non?',
    'tu savais que "Yagami" à l\'envers çà donne "I-m-a-gay"!?',
    'Keskispass ?',
    'Ben on est vendredi soir 19h00 et je suis encore au taf  uniquement parce que y a encore plein de monde qui reste là à bosser.',
    'J\'avais un truc prévu en plus.',
    'Bah qu\'est-ce t\'en as à foutre ? Tu peux pas te tirer ?',
    'Mais non je peux pas. Je suis le boss !!!!',
    'Ahaha. Ben raison de plus, non ? Tout le monde attend que le boss se tire le premier.',
    'Que dalle. C\'est le boss qui se tire en dernier et ferme la boutique.',
    'Hmm j\'imagine bien tout le monde en train de glander sur msn ou autre en se disant " putain mais quand est-ce que tout le monde se tire ? "',
    'Le pire c\'est que c\'est bien possible.',
    'Je confirme.',
    '...',
    'Thomas, c\'est bien toi ???',
    'Ah ben d\'accord en plus ils sont sur le chan.',
    'Derrière moi Paulette est en train de lire un webcomic. Pour ma part j\'étais absorbé par la contemplation d\'images de la Nasa. Les autres je sais pas mais ça a pas l\'air très productif en tout cas. ',
    'Ahahahaha !',
    'Mais bordel mais tirez-vous quoi !',
    'Je suis mort de rire.',
    'Bon ben je vais y aller alors.',
    'Tom, attends !',
    'Emmène les autres avec toi bordel.',
    'Dégagez tous.',
    'Ahaha quel patron !',
    'Ok ok je vais dire qu\'on y va.',
    'Ça c\'est du management !',
    'Ah putain ça bouge !',
    'Pas trop tôt !',
    'Je vais pouvoir partir bientôt.',
    'Fais gaffe à ce qu\'ils te guettent pas en bas de l\'immeuble pour voir combien de temps après eux tu sors :D',
    'Bah nan quand même pas.',
    'Tu crois ?',
    '...',
    'T\'es encore là ou t\'es déjà parti ?',
    'Nan je viens de vérifier par la fenêtre. Ils sont tous partis dans des directions différentes.',
    'Ahah ok.',
    'Bon ben je bouge alors.',
    'Ouais ok a+',
    'a+',
    'Et vive la vie en entreprise !',
    'Ta gueule.',
    'Tirage :',
    'E E N C U L E E S',
    'enculées',
    'enculées',
    'Plonk mène avec un mot de 8 lettres : ENCULEES.',
    'Praline n\'a pas mieux. Il faudra taper plus vite la prochaine fois ;)',
    'énucléées',
    'EthanQix remporte la manche avec un mot de 9 lettres : ENUCLEEES.',
    'EthanQix gagne 9 points. Score total : 33',
    'Oo',
    'bac + 5, les enfants ;)',
    'OH mec! Epic win hier!',
    '?',
    'Je passe à micromania et je demande la version collector de Darksiders 2',
    'bon elle est à 100 euros alors je passe à découvert',
    'Un léger, hein, mais bon je téléphone à mon banquier pour le prévenir, on sait jamais.',
    'Il décroche je lui explique et il me demande ce que j\'ai acheté , mal à l\'aise je lui dit ;',
    '"La version collector d\'un jeu vidéo..."',
    'Un peu irrité il me fait ; " Et ben, j\'espère que c\'est un bon jeu qui vaut le coup"',
    'Super mal je lui dit que le jeu en question c\'est Darksiders 2 et que je l\'attendais depuis longtemps, tout le blabla quoi.',
    'Et là il m’arrête et me dit "Darksiders 2 en collector à 100 euros?! Vous l\'avez trouvé où?"',
    'Du coup je lui ai dit ou trouver le jeu et il n\'a pas pris de charges sur mon découvert.',
    'J\'aime mon banquier &lt;3',
    'la lose, c\'est quand tu rates ton bus parce que t\'as perdu trop de temps à chercher le "6" de ton calendrier de l\'avent...',
    'la big lose, c\'est quand tu manges le mauvais chocolat....on est le 5 aujourd\'hui mec',
    'Tu va te foutre de moi et en rajouter.',
    'Mais non promis. Allez !',
    '... C\'est a cause de Cam.',
    'Elle est plus célib ?',
    'Non c\'est pas ça. Mais maintenant c\'est mort entre elle et moi, il se passera rien.',
    'Pourquoi t\'es pas son style ?',
    'Non je pense que je lui plaisait, mais j\'ai perdu beaucoup de charisme hier on va dire et je pense que ça a tout gaché.',
    'Explique.',
    'Tu sais que depuis un mois a peu pres on parle ensemble tout les soirs sur msn et qu\'on met la cam.',
    'Ouais et ?',
    'Ben si tu veux hier soir elle etait pas connectée, alors je me met un petit épisode de south park sur mon ordi portable et je vais le regarder aux chiottes. Donc j\'installe l\'ordi sur le meuble de la salle de bain en face des WC, ecran incliné vers moi. Et je matte mon épisode tranquille... Mais pendant que j\'avais la vidéo en plein écran elle se connecte a msn, me dit salut et met les deux cams. Le probleme c\'est que j\'etait en statut occupé donc je l\'ai pas entendu, et msn+ etait réglé sur "accepter toutes les requetes automatiquement"',
    'Donc elle ma regardé pendant a peu pres 15 min faire caca et moi pendant ce temps je rigolais comme un abruti a cause de l épisode.',
    'Je pense que c\'est irratrapable...',
    'Oo',
    'genre les cavaliers de l\'apocalypse vont prendre 5 mois pour ravager le monde. ',
    'c\'est n\'importe quoi',
    'On est 6 Milliards',
    'et on a des tanks',
    'Ils sont quatre',
    'avec des poneys',
    'BG69 has joined #rencontres',
    'slt T chode ?',
    'Comme la braise ;)',
    'tu fé koi ?',
    'La j’enlève ma main droite de ma souris, je la glisse vers mon entre-jambe... hum...',
    'Je passe sous mes sous-vêtements...',
    'Va y tu m\'exit',
    'chaudass va ;)',
    'Je descend ma main et, oh !',
    'va y continu',
    'UNE BITE !!!',
    'BG69 has quit #rencontres',
    'héhé, un de moins :D',
    'Vu dans une bijouterie : Les bagues volées doivent êtres ramenées et payées le double du prix initial...',
    'Non mais elle... ses connaissances en informatique se limitent à ouvrir Facebook et à y mettre "Tro bi1 Twilighte 4 !! Tro bo Edwouare !!"',
    'Sûr qu\'elle sait même pas ce que fait alt+F4, cette blondasse.',
    'Zaaa has left',
    'Zaaa has joined',
    'Euh...',
    'Sinon, fait beau chez vous ?',
    'Alors la rentrée c\'était comment ?',
    'Naze (la rentrée quoi). Et toi ?',
    'Moi la rentrée c\'est jeudi.',
    'On est pas dans le même lycée ?',
    '...',
    'zut',
    'Les meufs, ça a le goût de quoi le sperme?',
    'C\'est un peu salé, et un peu amère',
    '...',
    '...',
    '...',
    '...',
    'Enfin j\'imagine!!',
    'Putain les mec...',
    'Attends je screen',
    'mais pourquoi je viendrais chez toi, on s\'emmerde à chaque fois',
    'allez',
    'tu veux qu\'on fasse quoi ?',
    'je sais pas moi',
    'ben tu vois !',
    'mais il y a ma soeur qui bronze en mode top-less dans le jardin ...',
    'bon ...',
    'j\'ai pas le gout de te laisser tout seul toute la journée donc j\'arrive',
    'oh hier je suis sorti en boite de nuit..',
    'sérieux ? C\'était ta première fois non ?',
    'oui et la dernière de ma toute vie.. j\'étais avec une amie et je me suis habillé plutôt normalement. en arrivant devant la boite plutôt médiocre, y avait une file d\'attente énorme pour rentrer. une fois arrivé devant le videur et pensant rentrer sans problèmes je lui dis avec un grand sourire bonsoir. Il me répond "bonsoir, tas une ps3 ? "',
    '?',
    'intrigué par la question je lui répond oui évidemment...  et donc il me dit "bah retournes y jouer !"',
    'Pwned ¡¡¡',
    'et toi tu veux quoi pour ton anniversaire que je pourrais t\'offrir ?',
    'ta présence &lt;3',
    'c\'est vraiment beau ce que tu viens de dire',
    'je n\'ai même rien à ajouter ',
    'et une boite de chocolat aussi',
    'faut pas déconner quand même',
    '...',
    'j\'étais chez un pote',
    'je scanne les réseaux wifi et j\'en vois un dont le nom est "Ma voisine est ravissante !"',
    ':)',
    'et un peu plus bas "Voisine_pas_interessee"',
    '\o/',
    'Epic Win ce soir',
    'Vas-y raconte',
    'ce soir, soirée chez Chloé, ',
    'je sens l\'histoire drôle...',
    'on danse, on boit,',
    '(classique)',
    'et là, vers la fin, je fais un slow avec Chloé',
    'à la fin, je voulais dire un truc vachement romantique, du genre "t\'as d\'beaux yeux, tu sais"',
    'mais tout ce qu\'est sorti de ma bouche, c\'est "t\'es une vachement bonne cavalière..."',
    'elle m\'a regardé, elle a rigolé,',
    'Laisse moi deviner, elle est partie ?',
    'Non, elle m\'a dit droit dans les yeux :',
    '"Je suis une très bonne monture aussi..."',
    'Omg !',
    'Et le mieux, c\'est qu\'elle était totalement sobre :-)',
    'Et alors ? t\'as fait quoi ensuite ?',
    'du rodéo !!! :P',
    'Boy.',
    'Need ya d\'urgence.',
    'Oui?',
    'Je t\'écoute',
    'Tu saurais pénétrer dans les boîtes mails professionnelles de toute ma boîte ?',
    'Qu\'est ce que tu as fait de si grave?',
    'Y a eu le décès de l\'ancien boss récemment et l\'on m\'a chargé de taper un mail pour dire qu\'on était tous invités à l\'enterrement -Littéraire inside-.',
    'Et je viens de me rendre compte qu\'au lieu d\'inhumation, j\'ai écrit irrumation.',
    'Et c\'est?',
    'Google it.',
    'Oh putain',
    'Voilà.',
    'je crois que j\'ai couché avec quelqu\'un cette nuit',
    'du moins ce matin je me suis réveillé avec quelqu\'un dans mon lit et un préservatif usagé dans la poubelle',
    'cette personne s\'y trouve d\'ailleurs toujours mais compte tenu des quantités d\'alcool qu\'on a ingurgité hier soir je suis un peu confus quant à son identité',
    'quelle catégorie de confusion ?',
    'comment ça "catégorie" ?',
    'ben quand tu te réveilles avec quelqu\'un dans ton lit un lendemain de beuverie c\'est comme pour les tornades il y a plusieurs catégories',
    'Catégorie 1 : "c\'est quoi son prénom ?"',
    'Catégorie 2 : "elle ressemble à quoi déjà ?"',
    'Catégorie 3 : "c\'était bien une fille ?"',
    'heu...',
    'Catégorie 4',
    'hein ?',
    '"elle est encore vivante ?"',
    'Mon prof de géo est génial...',
    'Pk?',
    'Hier, il nous a donné un devoir à faire sur les différents types de volcans.',
    'Et il a aussi donné un lien youtube "seulement pour vous corriger une fois que vous avez fait l\'exercice !" a-t\'il dit.',
    'Alors bien sûr tout le monde a regardé la vidéo pour cheater.',
    'Ce matin il nous regarde tout sourire, et nous dit: "Alors combien d\'entre vous se sont fait Rick Rolled ?"',
    'Haha il m\'a tué mon père aujourd\'hui.',
    'Ça va être long ?',
    'Ta gueule, alors on était tout les deux dans le salon en train de boire une bière, moi je lui raconte un peu mes études comment ça ce passe et tout, ',
    'bref à partir de la on commence à déconner et à se raconter des blagues à la con.',
    'Et là je lui demande "au fait le vieux ça fait quoi d\'avoir le meilleur fils du monde ?" ',
    'Et la ce bâtard il me regarde et il me dit "je sais pas tu demanderas a ton grand père" ',
    'Da_Funk 0 /-/ Ton père 1',
    '.oO( at least thatd give Lightspark a reason to improve... )'
  ],
  topic: [
    '',
    'Fantome rejoint l\'équipe EpiKnet en tant que LocOp sur stdenis, merci à lui pour l\'hébergement de ce serveur pour EpiKnet.',
    '16/05/14 à 21h00 sur -#18-25ans - L\'équipe vous offre un Quizz de culture générale, venez nombreux y participer ! ',
    '26/04/14 21h00 -#Dialogues - Quizz culturel sur les films, séries télé et musiques, venez nombreux ! (Plus d\'infos) ',
    '18/04/2014 21h00 -#35+ans - Quizz de culture générale ! Venez nombreux passer un agréable moment avec nous ! ',
    'Félicitations à Dark qui devient le nouveau ChanAdmin du salon #Arts ! ',
    'Le serveur stdenis.fr.epiknet.org fournis par fantome entre dans sa période de test de liaison.',
    'Le serveur vitry.fr.epiknet.org rejoint le réseau ! Merci à Sendell de fournir ce serveur ',
    'Félicitations à XwZ et koollman qui passent Opérateurs des Services du réseau !',
    'Félicitations à J_C qui passe Administrateur des Services du réseau !',
    '14/03/14 au 30/03/14 -#Dialogues - Miss & Mister EpiKnet 2014 ! Venez vous inscrire et voter pour les Apollons et Vénus du réseau ! (Règlement & infos) ',
    'Félicitations à Kyle qui devient le nouveau ChanAdmin du salon #Jeux ! ',
    '01/02/14 au 15/02/14 -#Dialogues - BlindTest toute la journée pendant 15 jours, soyez nombreux ! (plus d\'infos) ',
    'Félicitations à Sleia qui devient la nouvelle ChanCoAdmin du salon #Dialogues ',
    'Bonne et heureuse année 2014, nous vous souhaitons d\'avoir la réussite, la santé et l\'amour ! ',
    '27/12/2013 21h - #18-25ans - Event Quizz culture Générale, venez nombreux ! ',
    '29/11/13 au 01/01/14 - #Dialogues - Event spécial Noel, soyez nombreux ! (plus d\'infos) ',
    'Félicitations à Majin qui devient le nouveau ChanAdmin du salon #Dialogues ',
    'Majin et Gurty passent HelpAdmin, Félicitations à tous les deux et bonne continuation !',
    'Les serveurs hub3.eu.epiknet.org et courbevoie2.fr.epiknet.org entrent dans leur période de test de liaison ! ',
    'Le serveur strasbourg.fr.epiknet.org tire sa révérence.'
  ]
};
