module.exports = {
  rooms: [
    '#toulouse', '#France', '#Paris', '#businessFR', '#paintball', '#chtis', '#MarseilleUno', '#dagnirDae', '#javascript',
    '#CastanetTolosan', '#KeepItFunky', '#General', '#Support', '#GirlsOnly', '#qsdqsdqd', '#html5', '#node', '#activeadmin',
    '#agilefr', '#amara', '#aptible', '#aspen', '#balanced', '#beets', '#bitledger', '#bountysource', '#camlistore', '#capisso',
    '#caravela', '#celery', '#chef', '#chef-hacking', '#chocolatey', '#cockroachdb', '#consul', '#coreos', '#crowbar',
    '#cryptography-dev', '#dat', '#daybed', '#deis', '#devcode.la', '#devopsru', '#distutils', '#django', '#django-cms',
    '#django-de', '#django-oscar', '#django-sprint', '#django-storages', '#docker', '#docker-dev', '#docpad', '#elixir-lang',
    '#esc', '#evehq', '#fluid-tech', '#fluid-work', '#flynn', '#forj', '#freeseer', '#frontendua', '#geppetto', '#gittip',
    '#gluster', '#gluster-dev', '#gocd', '#golang-id', '#go-nuts', '#google-containers', '#gpc-dev', '#hackedu',
    '#hackerspace-silesia', '#hackingscience', '#hangops_ru', '#haskell-id', '#Hawkthorne', '#hot', '#hypothes.is',
    '#inatri', '#INSMA', '#jekyll', '#jmonkeyengine', '#jpos', '#jsoxford', '#julython', '#kafka-python', '#kegbot',
    '#kievfprog', '#kitchenci', '#kivy', '#kivy-sdl2', '#lincolnloop', '#linuxonandroid-help', '#logstash', '#magnetodb',
    '#mailstache', '#mathquill', '#mayone', '#mayone-dev', '#mcollective', '#mcpedevs', '#mcserver', '#mopidy', '#n2o',
    '#nerdsummit', '#nixos', '#nycpython', '#octopress', '#okfn', '#opal', '#opencompanybiz', '#opencompanyorg', '#opendatatools',
    '#openobject', '#orain', '#orchardup', '#ossec', '#OtakuView', '#packer-tool', '#pelican', '#picrin', '#pithosio', '#plyer',
    '#pocketmine', '#pods', '#positivepython', '#proviso', '#puppet', '#puppet-dev', '#pyladies', '#pypy', '#pysthlm', '#python-eve',
    '#python-id', '#Pythonph', '#python-requests', '#quayio', '#racket', '#readthedocs', '#reddit-dev', '#restframework', '#rhodecode',
    '#rLSC', '#rust', '#rustdoc-wg', '#rust-gamedev', '#rust-internals', '#rustpkg-wg', '#scipy-conf', '#scrapy', '#scylla',
    '#sensu', '#sensu-casual', '#sentry', '#sequoiadb', '#serfdom', '#shields', '#shipyard', '#snabb', '#solidus', '#solum',
    '#sphinx-doc', '#stripe', '#swift-lang', '#swift-lang-ru', '#taarifa', '#tent', '#theodi', '#topaz', '#travis', '#UH-sky',
    '#unisson', '#unrealengine', '#uwsgi', '#vagrant', '#vespolina', '#waltz', '#wolfcms', '#xapian'
  ],
  messages: [
    'no :)',
    'confusing, eh',
    'rakudo-{parrot,jvm,moar} 28d672: OUTPUT«(timeout)»',
    '[+]() is just like foo()',
    'it is? o_O',
    'reductions are exactly like list operators, including the rule that parens make it a function call',
    'when would you want to call a reduction operator as a function?',
    'when you want to something else after as a postfix',
    'm: say [\+](1, 2, 3, 4, 5)[^2]',
    'rakudo-moar 28d672: OUTPUT«1 3␤»',
    'm: say [\+] (1, 2, 3, 4, 5)[^2] # as opposed to this',
    'rakudo-moar 28d672: OUTPUT«1 3␤»',
    'well, you lucked out :)',
    '...  er',
    'is quite tired, it seems',
    '… er indeed',
    'you see the difference with the infinite list, what with [+] being somewhat more eager than [\+]',
    'm: my $pair = (<this is>, <a list>, <of four>, <sublists>) => "Or is it?"; say $pair.key;',
    'rakudo-moar 28d672: OUTPUT«this is a list of four sublists␤»',
    'is new to [+] too :-\\',
    'earlier, it was implied that these lists flatten in the key',
    'they dont',
    'm: my $pair = (<this is>, <a list>, <of four>, <sublists>) => "Or is it?"; say $pair.key.perl',
    'rakudo-moar 28d672: OUTPUT«$(("this", "is"), ("a", "list"), ("of", "four"), "sublists")␤»',
    'see, the structure is still in the key',
    'oh!  I missed the \\',
    'm: say [\+] 1,2,3',
    'rakudo-moar 28d672: OUTPUT«1 3 6␤»',
    'note that it returns the same # of values, hence the [^2] worked either way',
    'despite doing the operations in the opposite order',
    'why I said "lucked out" :)',
    'right',
    'thanks,',
    'also now understands why [+]((11..*)[^14]) worked',
    'thought he was overriding presedence',
    'well foo() is very high precedence :)',
    'r: say [+].WHAT',
    'rakudo-{parrot,jvm,moar} 28d672: OUTPUT«(Int)␤»',
    'r: say &[+].WHAT',
    'rakudo-{parrot,jvm,moar} 28d672: OUTPUT«(Sub+{<anon>}+{Precedence})␤»',
    'verb vs noun',
    'on top of which, &[+] isnt a reduction',
    'its interesting that its sometimes easier to verb than to noun in perl6',
    'both FP and OO are biased in favor of verbs over nouns, though differently',
    'foo bar $baz vs $bas.bar.foo',
    'i thought in OO you usually cant have a verb without a noun to accompany it? :)',
    '.really?',
    'well, in java.',
    'remembers that article',
    'but you often want to call methods on something that is returned',
    'FP and OO just have different ways of cascading verbs',
    'ah, mhm',
    'http://outspeaking.com/words-of-technology/why-perl-didnt-win.html thats an interesting interpretation',
    '"Its *possible* that one of the Perl 6 works-in-progress will reach a point of usability and gain stability and maturity as a useful product, with documentation, libraries, support, and uptake." -- that was the important one for me.',
    'first off, while there have been many parallel efforts during the years, right now basically all the focus is on Rakudo and its backends.',
    'I understand if for a relative outsider that still looks like several works-in-progress. it doesnt feel like that from the inside.',
    'hrm, its not as bad as the python3 split, imo',
    'no? interesting.',
    'perl5 is not deprecated',
    'python upstream actively tries to get people to use py3, with the usual response of "lol" - who is going to port all the code for us?',
    'deprecation doesnt stop ~85% of the Python community from using Python 2.7',
    'well, circular - e.g. django, it now has theoretical py3 support, but practically thats still not production-ready',
    'so if I were starting any py project now, well, I still stick to py2',
    'thus all my effort goes into improving py2 libs. derp :D',
    'right.',
    'so the business case for py3 is, hmm, I spend a few hundred to a few thousand hours of effort on no visible progress, and get a performance penalty for that',
    'not something that interests me',
    'masak: is it a public holiday in Sweden today? Or is Austria divergently special?',
    'and where is TFM where I can R this?',
    'nwc10: no, today seems to be a workday. though I know some people who have a day off.',
    'nwc10: as to TFM, https://en.wikipedia.org/wiki/Public_holidays_in_Sweden seems to cover it fairly well.',
    'nwc10: that article even mentions "flag days", so it should suit you :P',
    'interesting. Articles on outspeaking.com dont have authors. They dont even have dates.',
    'how... convenient.',
    'hmmmm',
    'ahh, I think I know!',
    'FROGGS: method TOP',
    'yes yes',
    'that was just a thinko',
    'oh, you fixed it later.',
    'I have the problem that a native str is sneaked into the match objects of the token of a slang',
    'how sneaky.',
    'yeah....',
    'I turn v5 into pure Perl 6 atm... and that is an issue right now',
    'yay, it works :o)',
    'xfix: https://github.com/perl6/specs/commit/5cad8110c936c392b8a4304781ef767e1a7d7b0c -- the title says one thing (returns Int), but the patch says another (returns Rat).',
    'specs: 740854e | masak++ | S03-operators.pod:',
    'specs: actually mention that % does (Int, Int) -> Int',
    'specs: review: https://github.com/perl6/specs/commit/740854ee4d',
    'does S03 contain a type matrix somewhere?',
    '8 Jun 2014 21:11Z <raiph> moritz: Im trying to encourage a little cleanup of gh/perl6; please search for moritz in https://questhub.io/realm/perl/quest/534571eabbd0bed24e00006d TIA',
    '.tell raiph re perl6/p5-modules: you could contact the authors of the invidial modules, tell them to fork the repo (or extract subdirs) if theyre still interested',
    'moritz: Ill pass your message to raiph.',
    '.tell raiph ive updated rakudo.de a bit',
    'moritz: Ill pass your message to raiph.',
    'Hi all',
    'I have a noob question',
    'hi ennio',
    'Is there any difference between declaring a string in code and reading a string from a file with slurp',
    'ennio: the string in the code is in a constant table, because it will always be constant in your program',
    'the string from the file is not in that table of course',
    'Im not able to read a markdown file and parse it with Text::Markdown',
    'But it works with simple embedded strings',
    'so it seems that your are perhaps not reading the file in properly, or the file is misformatted',
    'ennio: can you no-paste your code?',
    'should look a bit like: say parse-markdown( "myfile".IO.slurp ).to_html',
    'https://gist.github.com/scriplit/7c9e86d0a8361dc41aa9',
    'ennio: I did this that way: https://github.com/sergot/filip.sergot.pl/blob/dee4c9cd235684e955e41053f20b1b735e531c55/gen.p6#L90',
    'but I didnt use slurp',
    'From embedded string:',
    '<strong>bold</strong> and <em>italic</em>',
    'From file:',
    '<strong>bold</strong> and <em>italic</em>',
    'ennio: it works on my box',
    'ennio: do you get an error message?',
    'No such method ast for invocant of type Any',
    'ennio: your gist certainly looks like it *should* work, both ways.',
    'ennio: if someone manages to reproduce your problem, we might be looking at a bug report here...',
    'ennio: btw. Text::Markdown has only bold, italics and code working iirc',
    'yeah, I should get on that :)',
    'the target feature set is "enough so that I can run my blog on it"...',
    'oh, FROGGS++ managed a non-reproduce above. I missed that.',
    'ennio: what is your perl6 --version?',
    '2014.05 on MoarVM',
    'hmmmm',
    'odd.',
    'ennio: can you please also pass --ll-exception when running the script? and then no-paste the backtrace?',
    'yes, thatll likely help a lot.',
    'ennio: work for me too',
    'works',
    'I mean, this can only mean that it failed to parse the document...',
    'arglbargl... porting EXPR from nqp to P6 is not that easy... "This type does not support associative operations"',
    'lunch &',
    'Ok, sorry my gist works actually - it breaks only if I add a newline at the end',
    '...of the md file',
    'Oh, true, thats weird, same here.',
    'that should be an easy fix to allow empty lines in the grammar at Markdown.pm at the bottom...',
    'ennio: I guess masak would be happy to recieve a pull request :o)',
    'Hmmm need to learn how to write a perl6 grammar first :-)',
    'ennio: it is just a classy form of a regex :o)',
    'good day',
    'hi timotimo',
    '.oO( is it? :P )',
    'I think so :o)',
    'well, except for the air conditioning of our server room at $work',
    '"classy form of regex", thats a good one',
    'FROGGS: is it supposed to be a public holiday in Germany?',
    'ie is your server room like the British weather - aware of the calendar',
    'nwc10: yes',
    'nwc10: err, that yes was about the holiday... and no, that air conditioning is just crappy',
    'newline at the end of file -- yes, happily accepting issues/pull requests for that.',
    'masak: https://github.com/masak/markdown/pull/1',
    'ennio++',
    'ooh',
    'ennio: hm, https://github.com/scriplit/markdown/commit/9c5ff28934d32f2b71acae46fa2f12d0ac19a1d6 doesnt look quite right.',
    'ennio: should probably still be [\n\n+]',
    'ennio:  could you fix that and, um, pull request again or something?',
    'Ithe \n+',
    'never will use irc fron my phone in the future :-)',
    'I dont know why but the constraint \n+ is not applied',
    'ennio: masak: itll work with [\n\n+] \n*',
    'Shouldnt it work without the \n* then?',
    'If we have no \n there it doesnt work with files containing empty lines, if we have \n+ there it deosnt work with just strings.',
    'to be precise: I was fine with the addition of \n* -- I dont see why the + inside the [\n\n+] was removed.',
    'that latter change seems unrelated to the PR, and so I dont want to accept it as it stands.',
    '(and if the tests still pass with that + gone, then were missing a test -- pull requests welcome) :)',
    'Nee',
    'Need to study a bit more to understand what this + does :-)',
    '<paragraph>* % [\n\n+] means "zero or more paragraphs, separated by two or more newline characters"',
    'your change makes that instead "...separated by exactly two newline characters"',
    'I mighta written taht as [\n ** 2..*]',
    'And more newlines are captured by \n* now',
    'Yes, but the \n* after it doesnt fall within the paragraph separator, no?',
    'If its <paragraph>* % [\n\n+] \n*',
    'what jnthn said.',
    'ennio: you dont seem to understand the % construct yet.',
    'ennio: <paragraph>* % [\n\n+] is one unit, tied together by the %',
    'ennio: the thing that comes after the % in the [] is a separator',
    'Ok',
    'hope that helps -- if not, ask more questions :)',
    'yawns.',
    'Segmentation fault',
    'make: *** [gen/parrot/stage1/NQPP6QRegex.pbc] Fehler 139',
    'epic fehl.',
    'groans',
    'nwc10: youre in 4th place for what I assume is the p5 code (merlyn wasnt too clear about which code base he was using)  Only about 60,000 more change lines and youll be in 2nd!   :)',
    'unclear too. ohloh puts me second by whatever metric they use: https://www.ohloh.net/p/perl/contributors/summary',
    'which might be number of commits. Not changes, not blame annotation',
    'typically, I think Ive been making smaller commits than the mean commit size (but more of them)',
    'and also Ive removed more lines of code that many people',
    'removal++',
    'although dont confuse "lines of files shipped in the tarball" with "lines of code" - davem removed a lot of Changes files, and Ive removed a lot of auto-generated stuff',
    'merlyns metric using "git blame" wont give you credit for the lines that arent there, but they are equally important (if not more important sometimes :)',
    'also, if I know what merlyns metric is, I can game it, by systmatically removing or changing lines of code of the people "ahead"',
    ':D',
    'assuming you actually care to game the metric :-)',
    'Im more curious what the stats are for Rakudo, and how to dilute the scors of the current metrics: https://www.ohloh.net/p/rakudo/contributors/summary',
    'scores of the current "winners"',
    'ie, how to broaden the contributor base',
    'lizmat++ is beating me in the last 12 months :)',
    'in particular, "Other" is slacking off. 17% all time, 15% last 12 months, and a mere 3% in the last month.',
    'I think that Rakudos code is easier to grok, so that barrier to entry is quite a bit lower than P5.  It seems the "big" problem for contributing is finding useful problems to work on  (or maybe finding problems to work on that arent being quickly solved by the existing contributor base)',
    'PerlJam: OK, so how could we make it easier to match such tasks to potential volunteers?',
    'well, I had an approach',
    'with weekly blog posts that invite people to solve very specific, approachable tasks',
    'I dunno.  Maybe a big list of the known problems along with some hints as to whats need to solve them (knowledge of grammars, concurrent programming, etc.)',
    'and it got us a few short-term and medium term contributors',
    'moritz++ thats sounds awesome.',
    'but I ran out of steam and ideas',
    'http://perlgeek.de/blog-en/perl-6/contribute-now-announce.html # from 2010',
    'IMHO, our biggest lack is documentation, tutorials, and whatever other "educational" materials we can generate to get people started *using* P6.',
    'Thats what I intend to do if I can ever find some time and get my head oriented right--write some stuff that helps people get started',
    '++PerlJam',
    'oh, Im in that newest list :o)',
    'pmichaud, coke and jnthn are the oldest in there',
    '(and probably the most profilic ones)',
    'moritz: re, running out of ideas ...   Couldnt we troll the RT tickets for ideas?  Or does the problem then become the time it takes to specify the problem enough so that someone can solve it?',
    'PerlJam: well, RT is full of stuff; sifting through it to find something that you are confident that is easy to fix is the problem. Plus writing up, yes',
    'maybe at the next YAPC, instead of a hackathon, there should be a specifiathon where we troll RT and pull out problems for people to solve and specify them enough so that others can contrubute.',
    'well ... by "we" I mean "you guys" because I wont be at YAPC this year :(',
    'PerlJam: well, the real problem is that this preparation needs to happen *before* the specifiathon',
    'aye.  That makes sense.',
    'we can start crowd-sourcing problems/tickets now, and then either use it for YAPC or blog-driven',
    'The beauty of a whatever-athon is that its designated time.  You know going in what youre going to be doing, so you prepare to do it.  If you try to do the same thing "in your spare time", you never have enough spare time to make significant progress.  (OR maybe thats just my personal problem)',
    'doing stuff in your spare time requires A LOT of organization',
    '(coke is the oldest where?)',
    '[Coke]: (contributor. one of the)',
    'Coke: ohloh says your first commit was "about 8 years ago"',
    'http://perl6.org/community/irc -> Much real-time discussion happens on our IRC channel, #perl6 or irc.freenode.net. ~~ s/or/on/ :)',
    'perl6.org: 625577f | moritz++ | source/community/irc.html:',
    'perl6.org: Fix typo, zengargoyle++',
    'perl6.org: review: https://github.com/perl6/perl6.org/commit/625577f044',
    'm: say "a" ~~ / . { $<O> := "ohh" } { $<sym> := $<OPER> } /;',
    'rakudo-moar 28d672: OUTPUT«｢a｣␤␤»',
    'm: say "a" ~~ / . { $<O> := "ohh";    $<sym> := $<OPER> } /;',
    'rakudo-moar 28d672: OUTPUT«===SORRY!===␤postcircumfix:<{ }> binding not defined for type Match␤»',
    'jnthn: what kind of bug is that ---^?',
    'is there a good p6 hacking document like perldoc perlhack* in p5?',
    'zengargoyle: thats a good question.',
    'i.e. from git clone to email patch',
    'you mean, from git clone to pull request? :-)',
    'no end-to-doc, Im afraid :(',
    'Theres a "Submitting Patches" section in README',
    'But yeah, its not end-to-end.',
    'and docs/arechiture.{svg,html} inside the rakudo repo',
    'zengargoyle: you can start a more comprehensive document if you like  :)',
    'for a broad overview',
    'There is a whole bunch of material on learning how the internals work.',
    'ah right, the excellent internals workshop',
    'https://github.com/edumentab/rakudo-and-nqp-internals-course',
    'http://edumentab.github.io/rakudo-and-nqp-internals-course/ # PDFs',
    'jnthn++ a thousand times over for that',
    'dijkmat++ # for buying the course and allowing it to be open-sourced',
    'aye',
    'lizmat++ woolfy++',
    'jnthn++ lizmat++ woolfy++',
    'Huh?  :-)',
    'jnthn++  everybody++  yeah++',
    'woolfy++! :P',
    'woolfy++ # double plus good.',
    'woolfy++ lizmat++  (because you guys can never have enough karma :)',
    'woolfy: denial is futile. Youre being ++ed, and you deserve it!',
    'Perhaps some day there will be another live running of the course. :)',
    'woolfy++ lizmat++ # indeed',
    's/guys/gals/  # oops :)',
    '(stop that incessant ringing!!!)',
    'woolfy++ # what ringing? I dont head anything.',
    'hear*',
    'masak',
    'masak',
    'masak',
    'What?',
    ':-)',
    'mushroom mushroom...',
    'heh. no sound here, just a small red number :)',
    'Hummm...',
    'is very sensitive to disruptions, and generally turns off any audial cues first thing he does',
    'gets lots of test failures in m-spectest',
    'moritz: I have no idea what youre talking about!',
    'rakudo-star-daily: 7f18ec9 | coke++ | log/ (12 files):',
    'rakudo-star-daily: today (automated commit)',
    'rakudo-star-daily: review: https://github.com/coke/rakudo-star-daily/commit/7f18ec9ef2',
    'rakudo-star-daily: 7eee221 | coke++ | log/ (13 files):',
    'rakudo-star-daily: today (automated commit)',
    '[Coke]: neither have I, unfortunately',
    'rakudo-star-daily: review: https://github.com/coke/rakudo-star-daily/commit/7eee221d9e',
    'rakudo-star-daily: a516f08 | coke++ | log/ (10 files):',
    'rakudo-star-daily: today (automated commit)',
    'rakudo-star-daily: review: https://github.com/coke/rakudo-star-daily/commit/a516f08dcb',
    'perl6-roast-data: 8875c21 | coke++ | / (6 files):',
    'perl6-roast-data: today (automated commit)',
    'perl6-roast-data: review: https://github.com/coke/perl6-roast-data/commit/8875c21138',
    'perl6-roast-data: 2780e63 | coke++ | / (6 files):',
    'perl6-roast-data: today (automated commit)',
    'perl6-roast-data: review: https://github.com/coke/perl6-roast-data/commit/2780e63c2f',
    'Jus curious, if a program is careful not to use local state, should be it possible to use channels to remember and replay events to create a debbuger that movte in time like swift of elm?',
    '* swift or elm',
    'moars only failure in yesterdays daily run is:',
    'S17-promise/allof.t 10 - got the right order',
    '[Coke]: and thats probably not reproducable',
    'bad test!',
    ':)',
    ':/',
    'S05-mass/properties-general.rakudo.jvm aborted 580 test(s)',
    'S05-mass/rx.rakudo.jvm aborted 473 test(s)',
    '(those are probably timeouts)',
    'Shame the bus number on the eval server is < 1',
    'Coke: jvm consistently needs more permgen to pass tests for me. I will provide a PR to patch the eval runner',
    'Hey, my show is over, and I might have something resembling rakudo time available…',
    'donaldh: the eval runner is busted, and doesnt work for me.',
    'always craps out about 2/3 of the way through the spec test. (I am using a runner in t/spec, not "make spectest")',
    'would your fix fix that/',
    '?',
    'Yes. I think the eval runner just needs more heap and more permgen to make it through consistently.',
    'Just need to test it through some more.',
    'lets just upgrade our java requirement to 8. :P',
    'm: for 1..* -> $i { last if $i > 5 };',
    'rakudo-moar 28d672: ( no output )',
    'well, yeah, it behaves better on 8',
    'donaldh: any reason why theres no output diagnostics when we run out of permgen?',
    ':x',
    'hugs sergot, good vi(m) user!',
    'rakudo.parrot also still not clean.',
    ';)))',
    'When I ^C on OSX I sometimes get a permgen error on the console.',
    '(after it has crapped out)',
    'ok. next rakudo thing for me: get a clean spec test run on all tiers. Then, when we get a failing test, go through the diffs in roast & rakudo & maybe nqp & parrot & moar, and start naming names.',
    's/tiers/backends/',
    '"oh no, jnthn, not again!" :P',
    'I KNOW ITS YOU, JNTHN!!!',
    'seriously, I dont know who it is, but these supply tests are fiddly.',
    'm: for 1..* -> $i { last if $i > 5; my $s = errmsg needed; }; say $s;',
    'ok, have to go get my work iphone diagnosed, and will return later. (diagnosis: its a brick)',
    'So, who declared a my $s in the setting body? :P',
    ':D',
    'src/core/JSON/Pretty.pm',
    '94:my $s = 2;',
    'looks like it can be removed',
    'Pretty leaky... :P',
    '/o\\',
    'sergot: will you remove it or shall I?',
    'lizmat: I can do this.',
    'm: say $sprintfHandlerInitialized;  sprintf("%d",42); say $sprintfHandlerInitialized;',
    'so, FROGGS added the $s :)',
    'masak: who said that? :P',
    'jnthn:  in that course on rakudo/nqp internals, does it mention that you need to be real careful about declaring variables in the setting?  :)',
    '...unless you consider that the module originally comes from https://github.com/FROGGS/p6-JSON-Pretty/ -- in which case FROGGS added the $s :P',
    'hmpf',
    'lizmat: have to go, Ill do this later :)',
    'ok',
    'PerlJam: No :P',
    'is there a matrix somewhere for the features Perlito6 supports?',
    'jnthn: <O(%additive)> is supposed to set $<O> since it returns a passing cursor, right?',
    'Yeah...soemthing like that',
    'I think there may be something a bit funky going on with the match object within it there...forget exactly.',
    'it puts a hash into the $!match',
    'ah, yeah...',
    'my problem is that <O> is an empty match :/',
    'Thats an...interesting trick. :)',
    'Have you compared NQPCursor.MATCH vs Cursor.MATCH?',
    'right now',
    'NQPCursor.MATCH also returns $!match when it is a list',
    'so, I should be able to work around that...',
    'list? or hash?',
    'hash',
    'sorry :o)',
    'walk, shopping...bbl &',
    'I am kind of surprised to find S20 empty',
    'dont we have a good story on that?',
    'Coke: https://github.com/rakudo/rakudo/pull/276',
    'Coke: This increases the permgen for the eval server. It works for me on OSX. I plan to run the tests with tweaked values to see if there is an optimal setting.',
    'rakudo/nom: c75e408 | (Donald Hunter)++ | tools/build/ (2 files):',
    'rakudo/nom: Give the eval server more heap and permgen.',
    'rakudo/nom: review: https://github.com/rakudo/rakudo/commit/c75e408b95',
    'rakudo/nom: dba10ee | moritz++ | tools/build/ (2 files):',
    'rakudo/nom: Merge pull request #276 from donaldh/eval_server',
    'rakudo/nom:',
    'rakudo/nom: Give the eval server more heap and permgen.',
    'rakudo/nom: review: https://github.com/rakudo/rakudo/commit/dba10ee20d',
    '... and fixes a missing dependency. donaldh++',
    'yep, that too :)',
    'bbl',
    'ok, Ill give that a shot with the test_summary version as soon as todays normal run completes. donaldh++',
    'any suggestions for this weeks weekly?',
    'timotimo: one can switch to a slang now like in this example: https://gist.github.com/FROGGS/2da7263ffe79d2a6465c#file-slang_example-pm6',
    'that patch at the top is in rakudo by now?',
    'a couple things went into STD that would probably be easy to port to rakudo',
    'std: my $;',
    'ooh',
    'std: / <[ "abc" ]> /',
    'FROGGS: FROGGS can a pure-perl6 slang now do lots of stuff or are there still plenty of landmines?',
    'TimToady++',
    'is much more excited about the slangs though :)',
    'timotimo: ahh wait, the needed patch is not yet in! (doh!)',
    'quickly! ;)',
    'timotimo: I dont know about landmines... I just see that v5 needs way more love before it will be in a good shape again :o)',
    'mhm',
    'rakudo crshes while compiling on recent mint',
    'any confirmation?',
    'rakudo/nom: 186f0e4 | (Tobias Leich)++ | src/Perl6/World.nqp:',
    'rakudo/nom: fix precomp bug about colonpairs in use statement',
    'rakudo/nom:',
    'rakudo/nom: When we pass a colonpair to a use statement it can land in the compiled',
    'rakudo/nom: compilation unit before the CUs serialization context is created. Which',
    'rakudo/nom: means that we cannot have WVal there, since these need the SC of the CU',
    'rakudo/nom: to be deserialized. This patch cares about strings, i.e. in :from.',
    'rakudo/nom: We need a smarter solution in future to be able to use regexes, versions',
    'rakudo/nom: and other objects in colonpairs there.',
    'rakudo/nom: review: https://github.com/rakudo/rakudo/commit/186f0e4679',
    'lichtkind: works on my ubuntu, thats all I know',
    'rakudo/nom: 5fad7c6 | (Tobias Leich)++ | src/Perl6/ModuleLoader.nqp:',
    'rakudo/nom: fix loading of NQP modules',
    'rakudo/nom:',
    'rakudo/nom: NQPs module loader does not know about the :$line named parameter.',
    'rakudo/nom: Also, when we run deserialization tasks we have no GLOBALish to pass,',
    'rakudo/nom: so dont pass any.',
    'rakudo/nom: review: https://github.com/rakudo/rakudo/commit/5fad7c6ead',
    'is anybody using v5 atm?',
    'FROGGS, in a slide deck, yes.  :-)  Why?',
    'japhb: I was thinking that my next patch might break it, but it does not :o)',
    'so, all is good :o9',
    ':o)',
    'lichtkind: I can compile rakudo fine on 64-bit gentoo, but panda fails.',
    '"This is perl6 version 2014.05-151-gdba10ee20da8 built on MoarVM version 2014.05-18-g6b19b4b2a463"',
    'FROGGS++',
    'after your last patch it works again',
    'rakudo/nom: 7606343 | (Tobias Leich)++ | src/Perl6/Grammar.nqp:',
    'rakudo/nom: allow to switch to a pure Perl 6 slang, not just NQP',
    'rakudo/nom:',
    'rakudo/nom: We are now very careful when calling into the foreign statementlist,',
    'rakudo/nom: and also when we get the match and the made result back, we turn this',
    'rakudo/nom: into a NQP-level match. This means that language switching is slightly',
    'rakudo/nom: more expensive then before, but the other approach would make grammars',
    'rakudo/nom: in general slower.',
    'rakudo/nom: review: https://github.com/rakudo/rakudo/commit/7606343572',
    'lichtkind: that is just coincident :o)',
    'but my data ... :)',
    ':o)',
    'timotimo: here you go :o)',
    'Right, panda has been failing on Rakudo-moar since last Thursday.',
    'colomon: I know it got isolated to a version bump; if its Moar-version sensitive then re-building Moar at some earlier versions could help track down what commit there broke it (though guess it could be an NQP one also)',
    'hugs #perl6',
    'no names, but wow some other IRC channels are puerile',
    'thank you, #perl6, for being worth talking to :)',
    'I love myself some masak hugging.',
    'Saw the patches sometime in the last week that made $*USER and $*GROUP work.  They are objects that .Numeric and .Str appropriately.  Is the true dualvar concept -- single values that ~~ Int and ~~ Str at the same time -- now dead?',
    'IntStr may well end up being more dualvar-ish, but doing that for $*USER and $*GROUP feels odd to me.',
    'Does IntStr work in Rakudo now?  (Did I just miss that happy moment?  :-)',
    'yeah, thats not really the intent of IntStr...',
    'Sigh, no joy from git grep',
    'NYI',
    'TimToady, I know the intent of IntStr was for e.g. command line args, but why *wouldnt* you use that for something like $*USER, assuming it worked?',
    'japhb_: I think using IntStr for something that isnt two representations of the same peice of information (like "42" and 42) is probably a bit of a design smell.',
    'Ah, I see.  That dividing line makes sense to me.',
    '+1 to what jnthn says.',
    '+1',
    'the concept youre grasping for is called "an object" with "accessors" :P',
    's/you/yall/',
    'masak, Im not grasping for anything -- and certainly not that.  Because for $*USER the stringy and numeric values are (nearly) equivalent identities.  In some sense japhb and 1234 are both ids.',
    'But I understand jnthns point of reserving dualvars for 1234 and 1234',
    'I guess my point was based on $*USER being nothing other than a caching container for the two equivalent IDs.',
    'lizmat: https://github.com/rakudo/rakudo/pull/277 - done :)',
    'It would have felt obviously object-ish if it carried other attributes of the user, like home directory, default shell, or full name.',
    'I dunno, to me its clearly a small struct-like object.',
    'oh, chrome disabled extensions installed from outside the store ? Looks like its time to get back to firefox.',
    'huh. JSON::Pretty is core now?',
    'aye.',
    'tadzik: it is :)',
    'wow',
    'is JSON core too? :D',
    '...no',
    'I have no words',
    'tadzik: how should I name the next release? :)',
    'sergot: Poznan? Or was there already Poznan, hmm',
    'there was already Poznan.',
    'sorry, already nabbed it last year :>',
    'thats the problem :P',
    'why do we have a json emitter but not a json parser in core-core?',
    'because something core needed the JSON emitter.',
    'and nothing core needs the JSON parser.',
    'oh wait, we do have the parser too',
    'tadzik: Something to do with it being a dependency of the S11 stuff.',
    'tadzik: Im guessing its being kept private to that...',
    'ah, ok',
    'm: say JSON::Pretty',
    'rakudo-moar dba10e: OUTPUT«===SORRY!===␤Could not find symbol &Pretty␤»',
    'Yeah.',
    'alrighty',
    'So its only there as an implementation detail, afaict. Which feels right, cus thats what it is.',
    'I guess',
    'Hi all.',
    'TimToady: here? May I PM you?',
    '.oO( IS IT OK IF I WHISPER IN YOUR EAR )',
    '.oO( Talk to me like coders do )',
    '.oO( $i++; # increase $i by one )',
    '.oO( Is that why you hugged us all before )',
    'masak: the comment wouldve actually read "# decrease $i by two" or somesuch because of implementation changes over time  :)',
    'PerlJam: my $four = 5; # set six to seven',
    ':P',
    '.oO( $price++; # if its special-offer Tuesday, the overload of ++ doesnt actually increment )',
    'q"" and qq and for (my $i = 0, $i < $n, $i++) {} :D',
    'jnthn: or more likely, that comment was never written.',
    'since we decided to become evil',
    'jnthn: youre the best kind of evil. Like C++ evi.',
    's/i\./il./',
    'vendethiel: sorry, Im having trouble reconciling C++ as "best evil" and somehow relating that to jnthn.',
    'PerlJam: actually, its evil operator overloading and C++',
    'we can do worse',
    'yes we can!',
    'I actually was thinking of C++ when I wrote it, but realized how easy it is to implement in Perl 6',
    'I hope we can, weve had so many years to learn',
    'jnthn: I knew it, somehow :P',
    'vendethiel++ psychic powers',
    'multi postfix:<++>(Price $p where Date.today.day == Tuesday) { $p } # :D',
    'baww',
    'I guess it cant decide :P',
    'yeah',
    'Need whitespace around infixen...',
    'As a postfix always wins',
    'that ruins the fun',
    'You can see that from the error.',
    'yeah',
    'jnthn: I panicked when I saw your suggestion -- I went "what, .day!? we have an enum with Tuesday in it!?"',
    ':P',
    '"...who designed that?"',
    'jnthn: (its .day-of-week and 2, respectively)',
    'thing is, I tried with multi postfix:<++> locally, and I couldnt get it to work :/',
    'so Id love to see a working solution.',
    'm: say Friday',
    'I...think Id prefer an enum :P',
    'masak: I agree on day-of-week; not sure why an enum of weekdays is alarming you? :)',
    'clearly tuesday should be spelled :2day',
    'm: enum Weekdays <Lundi Mardi Mercredi>;',
    'rakudo-moar 760634: ( no output )',
    'jnthn: can think of two reasons right off. (a) I didnt want any English names in the Temporal classes, and (b) the weekdays are 1-based, and it would be slightly surprising for an enum to be.',
    'masak: Id say the English day names are much more widely agreed on that which is the first day of the week... :)',
    '(Until you said it was 1-based, Id been assuming Sunday was day 0. Seriously.)',
    'I thought long and hard on that one.',
    'decided that for those who expect Sunday to be 0, they can easily $wd % 7 and get that result.',
    'but the other way is trickier.',
    'I still have no idea whats going on with the parts of the world who figure Sunday is first in the week ;)',
    'thats just... so wrong.',
    'it doesnt mesh well with the widely accepted meaning of "weekend", for example.',
    'From the reliable source of answers that gave us "how is babby formed": https://answers.yahoo.com/question/index?qid=20071014021709AA3MAO7',
    'Its so not agreed upon :)',
    'you expected the US to be sane?',
    'No, I expect to get an enum of names so I dont have to worry about this :P',
    'so if they are called "ugh", "meh", "bleurg", "wa :-(", "POETS!", "yay", "zzz" it doesnt matter to the program?',
    'jnthn: also from that page: "ISO prescribes Monday as the first day of the week with ISO-8601." -- the rest of DateTime intentionally stays very close to ISO-8601.',
    'nwc10: thank god its ughday.',
    'masak: Im not arguing for a change to "what is the first day".',
    '*nod*',
    'masak: the CLDR defines the first day of the week for different locales',
    'masak: Im arguing for not leaving people having to guess wrong, like I mighta :)',
    'http://www.unicode.org/reports/tr35/tr35-35/tr35-dates.html#Week_Data',
    'jnthn: I dont have a horse in this particular race. if you can get popular support for introducing a WeekDay enum, go ahead.',
    'OK :)',
    '...though I would prefer for the enum not to mess up the existing integer values, if nothing else for compatibilitys sake...',
    '(and because I did ponder it quite a lot, and I believe I got the "right" design choice)',
    'Yes, Im fine with the integer values.',
    'perl6-roast-data: 6d46d95 | coke++ | / (3 files):',
    'perl6-roast-data: today (automated commit)',
    'perl6-roast-data: review: https://github.com/coke/perl6-roast-data/commit/6d46d95337',
    '^^ rakudo.moar is clean again.',
    'parrot & jvm still dirty.',
    'so, yay for moar!',
    'ugh. test changes to use eval server... accidentaly rebuild rakudo-jvm (slooow)',
    'if only we had an eval server for nqp-jvm!',
    'is into the spec test run with the eval server .whee.',
    'sooo much faster.',
    'it just need to work out',
    'rakudo/nom: 7a6d6ec | sergot++ | src/core/JSON/Pretty.pm:',
    'rakudo/nom: my $s removed',
    'rakudo/nom:',
    'rakudo/nom: We dont want this variable to be in the config',
    'rakudo/nom: review: https://github.com/rakudo/rakudo/commit/7a6d6eca98',
    'rakudo/nom: a7dd964 | (Tobias Leich)++ | src/core/JSON/Pretty.pm:',
    'rakudo/nom: Merge pull request #277 from sergot/nom',
    'rakudo/nom:',
    'rakudo/nom: my $s removed',
    'rakudo/nom: review: https://github.com/rakudo/rakudo/commit/a7dd96476f',
    'an interesting case of the inverse of a once-and-only-once refactor being the right thing to do, due to surrounding forces.',
    'now if only we could get rid of $sprintfHandlerInitialized, $default, $Nan, and $Inf  ...   :)',
    'oh, and $UINT64_UPPER',
    'do we have anything that looks like (delimited) continuations ?',
    'Or are we bound to do this sort of stuff through macros',
    'gather/take is implemented in terms of delimited continuations',
    'vendethiel: TimToady has said pretty definitively that (beyond gather/take), delimited continuations arent going to be exposed in Perl 6 as first-class things.',
    'oh',
    'mh; I see.',
    'I can guess why, but meh :(',
    'vendethiel: mainly because all VMs well want to target wont have them.',
    'Good point, actually.',
    'DOH. I didnt update rakudo-jvm before trying this test.',
    'But its a really, really powerful feature. I guess I still will be able to rewrite stuff in macros, someday',
    'doh',
    'nqp::continuationcontrol',
    'vendethiel: *nod*',
    'vendethiel: believe me, Im thinking about it.',
    'masak: which part ?',
    'the precise relations between program fragments, macros, and delimited continuations.',
    'masak: I expected you to :)',
    'perl6-debug appears to be broken, explodes with "Start argument to substr out of range. Is: -1, should be in 0..0"',
    'both -m and -j',
    ':/',
    '... again?!',
    'yay, looks like v5s EXPR is working...',
    'now I just need to solve that bloody hang/infiniloop in token statement',
    'weird; rakudo.jvm test runs much faster with the latest eval server tweak, but the failures are different.',
    'is experiencing that too.',
    'm: use QAST:from; my $p = QAST::Node.new; sub foo($bar) { }; foo($p) # @jnthn: why? ó.ò',
    'FROGGS: cus QAST::Node isnt Any, and the NQP <=> Perl 6 interop stuff we could do with having isnt really there yet...',
    'hmmmm',
    'in method message... as if it explodes in a exception',
    'm: use QAST:from; my $p = QAST::Node.new; sub foo(Mu $bar) { }; foo($p)',
    'rakudo-moar a7dd96: ( no output )',
    'ahh, yeah',
    'Yes, its exploding trying to report the exception.',
    'of course',
    'jnthn++',
    'But the reason for the exception is the bind failure',
    'But in general we need to make other-language things appear to be any',
    '*Any',
    'Does rakudo build on freebsd?',
    'I think so, yes',
    'Does it need anything special?',
    'And/or are there dependencies documented anywhere?',
    'the dependencies depend on what you build',
    'look at moarvm.org when you want to build rakudo@moar',
    'you can also build rakudo for jvm, then you just need the jre and Perl 5 AFAIK',
    'if you build for parrot, then libicu would be nice to have',
    'I just had a really crazy idea... perlito allows perl6 to be compiled to javascript; javascript and actionscript are supersets of ECMAScript; how hard would it be to modify perlito to produce ECMAScript which can *either* as javascript *or* as actionscript?',
    'Running perl6 in a flash player could be really cool, I think',
    's/ as javascript/ be interpreted as javascript/; s/ as actionscript/ be compiled as actionscript/',
    '... flash player, seriously?',
    'that craps gotta die, my friend',
    'sadly, the subset of perl6 that perlito can do is quite limited',
    'night, #perl6',
    '.oO( at least thatd give Lightspark a reason to improve... )'
  ],
  topic: [
    '',
    'Fantome rejoint l\'équipe EpiKnet en tant que LocOp sur stdenis, merci à lui pour l\'hébergement de ce serveur pour EpiKnet.',
    '16/05/14 à 21h00 sur -#18-25ans - L\'équipe vous offre un Quizz de culture générale, venez nombreux y participer ! ',
    '26/04/14 21h00 -#Dialogues - Quizz culturel sur les films, séries télé et musiques, venez nombreux ! (Plus d\'infos) ',
    '18/04/2014 21h00 -#35+ans - Quizz de culture générale ! Venez nombreux passer un agréable moment avec nous ! ',
    'Félicitations à Dark qui devient le nouveau ChanAdmin du salon #Arts ! ',
    'Le serveur stdenis.fr.epiknet.org fournis par fantome entre dans sa période de test de liaison.',
    'Le serveur vitry.fr.epiknet.org rejoint le réseau ! Merci à Sendell de fournir ce serveur ',
    'Félicitations à XwZ et koollman qui passent Opérateurs des Services du réseau !',
    'Félicitations à J_C qui passe Administrateur des Services du réseau !',
    '14/03/14 au 30/03/14 -#Dialogues - Miss & Mister EpiKnet 2014 ! Venez vous inscrire et voter pour les Apollons et Vénus du réseau ! (Règlement & infos) ',
    'Félicitations à Kyle qui devient le nouveau ChanAdmin du salon #Jeux ! ',
    '01/02/14 au 15/02/14 -#Dialogues - BlindTest toute la journée pendant 15 jours, soyez nombreux ! (plus d\'infos) ',
    'Félicitations à Sleia qui devient la nouvelle ChanCoAdmin du salon #Dialogues ',
    'Bonne et heureuse année 2014, nous vous souhaitons d\'avoir la réussite, la santé et l\'amour ! ',
    '27/12/2013 21h - #18-25ans - Event Quizz culture Générale, venez nombreux ! ',
    '29/11/13 au 01/01/14 - #Dialogues - Event spécial Noel, soyez nombreux ! (plus d\'infos) ',
    'Félicitations à Majin qui devient le nouveau ChanAdmin du salon #Dialogues ',
    'Majin et Gurty passent HelpAdmin, Félicitations à tous les deux et bonne continuation !',
    'Les serveurs hub3.eu.epiknet.org et courbevoie2.fr.epiknet.org entrent dans leur période de test de liaison ! ',
    'Le serveur strasbourg.fr.epiknet.org tire sa révérence.'
  ]
};
